version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Downloading Conformity Template Scanner binary..."
      - curl -L -o scanner https://github.com/awslabs/cloud-one-conformity-template-scanner/releases/latest/download/conformity-template-scanner-linux-x86_64
      - chmod +x scanner
  build:
    commands:
      - echo "Running security scan..."
      - ./scanner scan -f template.yaml -o results.json || exit 1

artifacts:
  files:
    - results.json
